### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by zinootje** [www5226448/web3s#1]
`(venv) C:\Users\***\pythonProject1>pip install web3s
Collecting web3s
  Downloading web3s-4.8.41.tar.gz (91 kB)
     |████████████████████████████████| 91 kB 1.5 MB/s
ERROR: Requested web3s from https://files.pythonhosted.org/packages/7c/36/22023b3b1c8bc594dda89f4fff352e08cd77646ff49aac900d286109f996/web3s-4.8.41.tar.gz#sha256=269aabbc1b23aca5b994fa
79c87c591f40c548a6226630d43a48fbddb003438b has different version in metadata: '4.8.4'
`

**Comment by www5226448** [comment]
You can install it by the asset in the releases.
