### ISSUE TITLE
Web3s instead of Web3 in ens/utils.py

### ISSUE THREAD

**Issue by inefix** [www5226448/web3s#3]
Dear @www5226448 ,

First of all thank you for this really nice library.

I think that in the file ens/utils.py at line 164, 171 and 182 you meant Web3s instead of Web3 right ?

Thank you again for your work.

Best regards

**Comment by www5226448** [comment]
Yes,but I hasn't tested the ens module.
please use carefully.

**Comment by www5226448** [comment]
Because this package's using scenario,the ens module has been removed.
